export const DIRECTOR_REQUEST = 'DIRECTOR_REQUEST';
export const DIRECTOR_ERROR = 'DIRECTOR_ERROR';
export const DIRECTOR_ADD = 'DIRECTOR_ADD';
// const DIRECTOR_REMOVE = 'DIRECTOR_REMOVE';
export const DIRECTOR_MOVIE_TOGGLE_SEEN = 'DIRECTOR_TOGGLE_MOVIE_SEEN';
